# Uncomment this line to define a global platform for your project
#platform :ios, ‘9.0’
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
target 'shoppingCart' do

    use_frameworks!

    pod 'SnapKit'

end
